/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototipo;

import desplazable.Desface;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author El!an
 */
public class Prototipo extends javax.swing.JFrame {

    /**
     * Creates new form Prototipo
     */
    Desface desplace;
    private int xMouse;
    private int yMouse;

    public Prototipo() {
        initComponents();
        desplace = new Desface();
        mostar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        MenuPlegable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Inicio = new javax.swing.JPanel();
        favicon = new javax.swing.JLabel();
        Clientes = new javax.swing.JPanel();
        Tabla = new javax.swing.JPanel();
        favicon4 = new javax.swing.JLabel();
        Scroll = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        IngresarBtn = new javax.swing.JPanel();
        Ingresartxt = new javax.swing.JLabel();
        EliminarBtn = new javax.swing.JPanel();
        Eliminartxt = new javax.swing.JLabel();
        ModificarBtn = new javax.swing.JPanel();
        Modificartxt = new javax.swing.JLabel();
        Factura = new javax.swing.JPanel();
        favicon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(251, 248, 241));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(251, 248, 241));

        exitTxt.setBackground(new java.awt.Color(251, 248, 241));
        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(84, 186, 185));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        header.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 40, 40));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 40));

        MenuPlegable.setBackground(new java.awt.Color(247, 236, 222));
        MenuPlegable.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(84, 186, 185));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/factura2.png"))); // NOI18N
        jLabel1.setText("Citas");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel1.setIconTextGap(15);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        MenuPlegable.add(jLabel1);
        jLabel1.setBounds(0, 150, 220, 50);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu2.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        MenuPlegable.add(jLabel2);
        jLabel2.setBounds(0, 10, 220, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(84, 186, 185));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/inicio2.png"))); // NOI18N
        jLabel3.setText("Inicio");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel3.setIconTextGap(15);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        MenuPlegable.add(jLabel3);
        jLabel3.setBounds(0, 50, 220, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(84, 186, 185));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/usuario2.png"))); // NOI18N
        jLabel4.setText("Clientes");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel4.setIconTextGap(15);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        MenuPlegable.add(jLabel4);
        jLabel4.setBounds(0, 100, 220, 50);

        jPanel1.add(MenuPlegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 670));

        Inicio.setBackground(new java.awt.Color(233, 218, 193));
        Inicio.setPreferredSize(new java.awt.Dimension(50, 560));

        favicon.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        favicon.setForeground(new java.awt.Color(255, 255, 255));
        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo1.png"))); // NOI18N
        favicon.setText("Clinica La Esperanza");

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                .addContainerGap(771, Short.MAX_VALUE)
                .addComponent(favicon)
                .addGap(23, 23, 23))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favicon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
        );

        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1220, 670));

        Clientes.setVisible(false);
        Clientes.setBackground(new java.awt.Color(204, 255, 255));
        Clientes.setPreferredSize(new java.awt.Dimension(50, 560));

        Tabla.setBackground(new java.awt.Color(239, 255, 253));
        Tabla.setPreferredSize(new java.awt.Dimension(50, 560));
        Tabla.setLayout(null);

        favicon4.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        favicon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo1.png"))); // NOI18N
        favicon4.setText("Clinica La Esperanza");
        Tabla.add(favicon4);
        favicon4.setBounds(760, 10, 426, 91);

        Scroll.setBackground(new java.awt.Color(239, 255, 253));
        Scroll.setBorder(null);
        Scroll.setToolTipText("");
        Scroll.setOpaque(false);

        jTable1.setBackground(new java.awt.Color(133, 244, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Edad", "Telefono", "Correo", "Fecha de nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(24);
        jTable1.setSelectionBackground(new java.awt.Color(66, 194, 255));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        Scroll.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(35);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(45);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(2);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(75);
        }

        Tabla.add(Scroll);
        Scroll.setBounds(100, 110, 1100, 410);

        IngresarBtn.setBackground(new java.awt.Color(84, 186, 185));

        Ingresartxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Ingresartxt.setText("Ingresar");
        Ingresartxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresartxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresartxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresartxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout IngresarBtnLayout = new javax.swing.GroupLayout(IngresarBtn);
        IngresarBtn.setLayout(IngresarBtnLayout);
        IngresarBtnLayout.setHorizontalGroup(
            IngresarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ingresartxt)
                .addGap(24, 24, 24))
        );
        IngresarBtnLayout.setVerticalGroup(
            IngresarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ingresartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Tabla.add(IngresarBtn);
        IngresarBtn.setBounds(100, 540, 100, 40);

        EliminarBtn.setBackground(new java.awt.Color(84, 186, 185));

        Eliminartxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Eliminartxt.setText("Eliminar ");
        Eliminartxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminartxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminartxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminartxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EliminarBtnLayout = new javax.swing.GroupLayout(EliminarBtn);
        EliminarBtn.setLayout(EliminarBtnLayout);
        EliminarBtnLayout.setHorizontalGroup(
            EliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Eliminartxt)
                .addContainerGap())
        );
        EliminarBtnLayout.setVerticalGroup(
            EliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Eliminartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Tabla.add(EliminarBtn);
        EliminarBtn.setBounds(220, 540, 100, 40);

        ModificarBtn.setBackground(new java.awt.Color(84, 186, 185));

        Modificartxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Modificartxt.setText("Modificar");
        Modificartxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificartxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModificartxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModificartxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ModificarBtnLayout = new javax.swing.GroupLayout(ModificarBtn);
        ModificarBtn.setLayout(ModificarBtnLayout);
        ModificarBtnLayout.setHorizontalGroup(
            ModificarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Modificartxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        ModificarBtnLayout.setVerticalGroup(
            ModificarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Modificartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Tabla.add(ModificarBtn);
        ModificarBtn.setBounds(340, 540, 110, 40);

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        jPanel1.add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1220, 670));

        Factura.setBackground(new java.awt.Color(255, 255, 204));
        Factura.setPreferredSize(new java.awt.Dimension(50, 560));

        favicon2.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        favicon2.setForeground(new java.awt.Color(255, 255, 255));
        favicon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo1.png"))); // NOI18N
        favicon2.setText("Clinica La Esperanza");

        javax.swing.GroupLayout FacturaLayout = new javax.swing.GroupLayout(Factura);
        Factura.setLayout(FacturaLayout);
        FacturaLayout.setHorizontalGroup(
            FacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FacturaLayout.createSequentialGroup()
                .addContainerGap(771, Short.MAX_VALUE)
                .addComponent(favicon2)
                .addGap(23, 23, 23))
        );
        FacturaLayout.setVerticalGroup(
            FacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
        );

        jPanel1.add(Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1220, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       //Despliega el menu dependiendo la poscision.
        if (MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -170, 10, 5);

        } else if (MenuPlegable.getX() == -170) {
            desplace.desplazarDerecha(MenuPlegable, MenuPlegable.getX(), 0, 10, 5);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
       //Redimensiona el componente para ecitar errores al momento de desplazarce.
        MenuPlegable.setSize(new Dimension(MenuPlegable.getWidth(), this.getHeight()));
    }//GEN-LAST:event_formComponentResized

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);//Sale del programa

    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        //hover de la X en rojo
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(new Color(251, 248, 243));
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        //hover regresando al color original
        exitBtn.setBackground(new Color(251, 248, 243));
        exitTxt.setForeground(new Color(84, 186, 185));
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
       //Obtine la poscicion del Header
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        //Mueve el programa a la poscicion arrastrada
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged
    
    
//Mustra panel visible inicio y cierra el menu desplegable
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Inicio.setVisible(true);
        Clientes.setVisible(false);
        Factura.setVisible(false);
        if (MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -170, 10, 5);
        }

    }//GEN-LAST:event_jLabel3MouseClicked
//Mustra panel visible Cliente y cierra el menu desplegable
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Inicio.setVisible(false);
        Clientes.setVisible(true);
        Factura.setVisible(false);
        if (MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -170, 10, 5);
        }
    }//GEN-LAST:event_jLabel4MouseClicked
//Mustra panel visible Factura y cierra el menu desplegable
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Inicio.setVisible(false);
        Clientes.setVisible(false);
        Factura.setVisible(true);
        if (MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -170, 10, 5);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void IngresartxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresartxtMouseClicked

    }//GEN-LAST:event_IngresartxtMouseClicked

    private void IngresartxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresartxtMouseEntered
        IngresarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_IngresartxtMouseEntered

    private void IngresartxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresartxtMouseExited
        IngresarBtn.setBackground(new Color(84,186,185));
    }//GEN-LAST:event_IngresartxtMouseExited

    private void EliminartxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminartxtMouseClicked

    }//GEN-LAST:event_EliminartxtMouseClicked

    private void EliminartxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminartxtMouseEntered
        EliminarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_EliminartxtMouseEntered

    private void EliminartxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminartxtMouseExited
        EliminarBtn.setBackground(new Color(84,186,185));
    }//GEN-LAST:event_EliminartxtMouseExited

    private void ModificartxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificartxtMouseClicked
        
    }//GEN-LAST:event_ModificartxtMouseClicked

    private void ModificartxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificartxtMouseEntered
        ModificarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_ModificartxtMouseEntered

    private void ModificartxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificartxtMouseExited
         ModificarBtn.setBackground(new Color(84,186,185));
    }//GEN-LAST:event_ModificartxtMouseExited
void mostar(){
    Color myColor = new Color(239,255,253);
    Scroll.getViewport().setBackground(myColor);
    jTable1.getTableHeader ().setFont (new Font ("Segoe UI", Font.BOLD, 12));
    jTable1.getTableHeader ().setOpaque (false);
     jTable1.getTableHeader ().setForeground (myColor);
    jTable1.getTableHeader ().setForeground (new Color (255, 255, 255));
    DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
headerRenderer.setBackground(new Color(66,194,255));

for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
}
    conexionBD conex=new conexionBD();         
    ResultSet r = conex.consultar("SELECT * FROM cliente");
    DefaultTableModel modelo = new DefaultTableModel();   
    modelo = (DefaultTableModel)jTable1.getModel();
     modelo.setRowCount(0); 
    try {
            while(r.next()){
            modelo.addRow(new Object[]{r.getString("idc"),r.getString("nombre"),r.getString("apellido"),
            r.getString("edad"),r.getString("telefono"),r.getString("mail"),r.getString("fechan")});
         
            }              
               jTable1.setModel(modelo);
                
                } catch (SQLException ex){
            Logger.getLogger(Prototipo.class.getName()).log(Level.SEVERE, null, ex);
        }    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prototipo().setVisible(true);
                
                
                

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel EliminarBtn;
    private javax.swing.JLabel Eliminartxt;
    private javax.swing.JPanel Factura;
    private javax.swing.JPanel IngresarBtn;
    private javax.swing.JLabel Ingresartxt;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel MenuPlegable;
    private javax.swing.JPanel ModificarBtn;
    private javax.swing.JLabel Modificartxt;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JPanel Tabla;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel favicon;
    private javax.swing.JLabel favicon2;
    private javax.swing.JLabel favicon4;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
